export const

  STATUS_ERROR = 500,
  STATUS_SUCCESS = 200,
  STATUS_NOT_CHANGE = 203,
  SHOW_ERROR = 'SHOW_ERROR',
  SHOW_SUCCESS = 'SHOW_SUCCESS',
  SHOW_INFO = 'SHOW_INFO',
  ACTION_TYPE_PROMISE = 'ACTYON_TYPE_PROMISE',
  ACTION_TYPE_PROMISE_SIMPLE = 'ACTION_TYPE_PROMISE_SIMPLE',

  LOGIN_REQUEST = 'LOGIN_REQUEST',
  SIGN_UP_REQUEST = 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  USER_SET_TOKEN = 'USER_SET_TOKEN',
  USER_LOGOUT = 'USER_LOGOUT',

  URL_BASE = 'http://localhost:4000',

  URL_AUTH = '/auth/login',
  URL_SIGN_UP = '/auth/sign-up',

  URL_SAVE_ORIGIN_AVATAR = '/image/save-origin',

  ////MAIN PAGE
  CHANGE_MODAL_STEP = 'CHANGE_MODAL_STEP',
  DELETE_PREVIEW_IMAGE = 'DELETE_PREVIEW_IMAGE',
  SET_PREVIEW_IMAGE = 'SET_PREVIEW_IMAGE',
  SEND_ORIGIN_AVATAR = 'SEND_ORIGIN_AVATAR';
  
